# Welcome to Jekyll!
title: Guilhem Barboux
email: guilhembarboux@gmail.com
tel: 783238570
adress:
  addressLocality: Paris
birthday: "1993-01-26"
description: >
  Guilhem Barboux
baseurl: "/"
url: "http://guilhembarboux.fr"
language: fr
languages:
  - en
links:
  - path: https://www.linkedin.com/in/guilhembarboux/
    label: Linkedin
  - path: http://www.viadeo.com/p/002riwz3096irhb
    label: Viadeo
  - path: https://github.com/GuilhemBarboux
    label: Github
lang:
  - label: Fr
    path: /
  - label: En
    path: /en/

# Build settings
source: ./site
markdown: kramdown
sass:
  sass_dir: assets/styles
  load_paths:
      - assets/styles
      - assets/libs/bootstrap-sass/assets/stylesheets
  style: compressed
  precision: 10
plagins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - assets/**.html
include:
  - robots.txt