# Welcome to Jekyll!
title: Guilhem Barboux
email: guilhembarboux@gmail.com
tel: 783238570
adress:
  city: Montpellier
description: >
  Guilhem Barboux
baseurl: "/"
url: "http://guilhembarboux.fr"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
source: site
markdown: kramdown
sass:
  sass_dir: assets/styles
  load_paths:
      - assets/libs/bootstrap-sass/assets/stylesheets
  style: compressed
  precision: 10
gems:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
